In [1]:
## for data
import pandas as pd
import numpy as np
from sklearn import feature_extraction, model_selection, naive_bayes, pipeline, manifold, preprocessing, metrics
## for word embedding
import gensim
import gensim.downloader as gensim_api
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
import seaborn as sns
import matplotlib.pyplot as plt
import pickle

In [ ]:
model_frWac_skip = gensim.models.KeyedVectors.load_word2vec_format("frWac_no_postag_no_phrase_500_skip_cut100.bin", binary=True, unicode_errors="ignore")
model_frWac = gensim.models.KeyedVectors.load_word2vec_format("frWac_no_postag_no_phrase_500_cbow_cut100.bin", binary=True, unicode_errors="ignore")

In [ ]:
df = pd.read_pickle(r'final1000.pickle')

In [38]:
df["phrases"] = df["text"].apply(lambda x: 
          [sentence.strip() for sentence in x.split("\n") if sentence])
df["tokens"] = df["text"].apply(lambda x: [token for token in x.replace("\n"," ").split(" ") if token])
# create the corpus of phrases of 1000 articles
liste_phrases_1000 = [y.split(" ") for x in df["phrases"].tolist() for y in x]

In [197]:
df

label                                               text  \
0       economie  syndicat patronat entendre sauver retraite com...   
1       economie  premier centrale nucléaire flottant monde rout...   
2       economie  Google Apple sceller rupture \n\nGoogle Apple ...   
3       economie  année exécrable marché emploi cadre \n\nmarché...   
4       economie  SoLocal ex-PagesJaunes conflit durcivre \n\nsi...   
...          ...                                                ...   
19395  politique  François Bayrou implacable procureur Nicolas S...   
19396  politique  François Hollande plaider faveur nouveau instr...   
19397  politique  Canard enchaîner Georges Tron louer bien appar...   
19398  politique  sortie réussie Nicolas Sarkozy \n\nregarder fa...   
19399  politique  Pen Estrosi favorable référendum immigration \...   

                                                 phrases  \
0      [syndicat patronat entendre sauver retraite co...   
1      [premier centrale nucléaire flottant monde rou...   
2      [Google Apple sceller rupture, Google Apple al...   
3      [année exécrable marché emploi cadre, marché t...   
4      [SoLocal ex-PagesJaunes conflit durcivre, situ...   
...                                                  ...   
19395  [François Bayrou implacable procureur Nicolas ...   
19396  [François Hollande plaider faveur nouveau inst...   
19397  [Canard enchaîner Georges Tron louer bien appa...   
19398  [sortie réussie Nicolas Sarkozy, regarder fair...   
19399  [Pen Estrosi favorable référendum immigration,...   

                                                  tokens  
0      [syndicat, patronat, entendre, sauver, retrait...  
1      [premier, centrale, nucléaire, flottant, monde...  
2      [Google, Apple, sceller, rupture, Google, Appl...  
3      [année, exécrable, marché, emploi, cadre, marc...  
4      [SoLocal, ex-PagesJaunes, conflit, durcivre, s...  
...                                                  ...  
19395  [François, Bayrou, implacable, procureur, Nico...  
19396  [François, Hollande, plaider, faveur, nouveau,...  
19397  [Canard, enchaîner, Georges, Tron, louer, bien...  
19398  [sortie, réussie, Nicolas, Sarkozy, regarder, ...  
19399  [Pen, Estrosi, favorable, référendum, immigrat...  

[3000 rows x 4 columns]

In [48]:
from gensim.models import Word2Vec
model_1000_100dim = Word2Vec(liste_phrases_1000)
model_1000_200dim = Word2Vec(liste_phrases_1000,size = 200)
model_1000_500dim = Word2Vec(liste_phrases_1000,size = 500)
model_1000_1000dim = Word2Vec(liste_phrases_1000,size = 1000)

In [198]:
model_1000_100dim.save("model_1000_100dim.model")
model_1000_200dim.save("model_1000_200dim.model")
model_1000_500dim.save("model_1000_500dim.model")
model_1000_1000dim.save("model_1000_1000dim.model")

In [127]:
# create the corpus of phrases of 8200 articles
df_8200 = pd.read_pickle(r'final8200.pickle')
df_8200["phrases"] = df_8200["text"].apply(lambda x: 
          [sentence.strip() for sentence in x.split("\n") if sentence])
df_8200["tokens"] = df_8200["text"].apply(lambda x: [token for token in x.replace("\n"," ").split(" ") if token])
liste_phrases_8200 = [y.split(" ") for x in df_8200["phrases"].tolist() for y in x]

In [129]:
model_8200_100dim = Word2Vec(liste_phrases_8200)
model_8200_200dim = Word2Vec(liste_phrases_8200,size = 200)
model_8200_500dim = Word2Vec(liste_phrases_8200,size = 500)
model_8200_1000dim = Word2Vec(liste_phrases_8200,size = 1000)

In [200]:
model_8200_100dim.save("model_8200_100dim.model")
model_8200_200dim.save("model_8200_200dim.model")
model_8200_500dim.save("model_8200_500dim.model")
model_8200_1000dim.save("model_8200_1000dim.bin")

In [150]:
# min_count, default = 5
model_8200_500dim_50cutoff = Word2Vec(liste_phrases_8200,size = 500, min_count = 50)
model_8200_500dim_100cutoff = Word2Vec(liste_phrases_8200,size = 500,min_count = 100)
model_8200_500dim_200cutoff = Word2Vec(liste_phrases_8200,size = 500,min_count = 200)

In [201]:
model_8200_500dim_50cutoff.save("model_8200_500dim_50cutoff.model")
model_8200_500dim_100cutoff.save("model_8200_500dim_100cutoff.model")
model_8200_500dim_200cutoff.save("model_8200_500dim_200cutoff.model")

In [202]:
# load a wordvector model
hehe = Word2Vec.load("model_8200_500dim_200cutoff.model")

In [203]:
hehe.most_similar("économie")

[('croissance', 0.4628686010837555),
 ('productif', 0.4453972578048706),
 ('finance', 0.43670880794525146),
 ('relance', 0.4341583251953125),
 ('déséquilibre', 0.43389129638671875),
 ('transition', 0.4282788038253784),
 ('budget', 0.41785717010498047),
 ('industrie', 0.41529279947280884),
 ('cohésion', 0.4104558825492859),
 ('compétitivité', 0.4094610810279846)]

In [66]:
def document_vector(text,model):
    """Create document vectors by averaging word vectors. Remove out-of-vocabulary words."""
    doc = [word for word in text if word in model.wv.vocab]
    vector = np.mean(model[doc], axis=0)
    return vector

In [115]:
from sklearn.metrics import accuracy_score
def compare_categ_log(categories,df,model_vec,dim):
    df_sampled = df[df['label'].isin(categories)]
    ## split dataset
    df_train, df_test = model_selection.train_test_split(df_sampled, test_size=0.3)
    ## get target
    y_train = df_train["label"].values
    y_test = df_test["label"].values
    df_train['doc_vector'] = df_train.tokens.apply(document_vector,model=model_vec)
    df_test['doc_vector'] = df_test.tokens.apply(document_vector,model=model_vec)
    train = df_train['doc_vector'].tolist()
    test = df_test['doc_vector'].tolist()
    clf = LogisticRegression().fit(train,y_train)
    y_pred=clf.predict(test)
    cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
    print(str(dim)+" dimensions accuracy: "+str(accuracy_score(y_test, y_pred)))
    # print(classification_report(y_test, y_pred))
    # fig, ax = plt.subplots()
    # classes = np.unique(y_test)
    # sns.heatmap(cnf_matrix, annot=True, fmt='d', ax=ax, cmap=plt.cm.Blues, 
    #             cbar=False)
    # ax.set(xlabel="Pred", ylabel="True", xticklabels=classes, 
    #     yticklabels=classes, title="Confusion matrix")
    # plt.yticks(rotation=0)

In [133]:
compare_categ_log(["economie","politique"],df,model_1000_100dim,100)
compare_categ_log(["economie","politique"],df,model_1000_200dim,200)
compare_categ_log(["economie","politique"],df,model_1000_500dim,500)
compare_categ_log(["economie","politique"],df,model_1000_1000dim,1000)

100 dimensions accuracy: 0.8683333333333333
200 dimensions accuracy: 0.8616666666666667
500 dimensions accuracy: 0.8666666666666667
1000 dimensions accuracy: 0.8566666666666667


In [134]:
compare_categ_log(["economie","politique"],df,model_8200_100dim,100)
compare_categ_log(["economie","politique"],df,model_8200_200dim,200)
compare_categ_log(["economie","politique"],df,model_8200_500dim,500)
compare_categ_log(["economie","politique"],df,model_8200_1000dim,1000)

100 dimensions accuracy: 0.9233333333333333
200 dimensions accuracy: 0.925
500 dimensions accuracy: 0.905
1000 dimensions accuracy: 0.9166666666666666


In [151]:
print("cutoff 500dim") # amelioration vs 0.905
compare_categ_log(["economie","politique"],df,model_8200_500dim,100)
compare_categ_log(["economie","politique"],df,model_8200_500dim_50cutoff,200)
compare_categ_log(["economie","politique"],df,model_8200_500dim_100cutoff,500)
compare_categ_log(["economie","politique"],df,model_8200_500dim_200cutoff,1000)

cutoff 500dim
100 dimensions accuracy: 0.9283333333333333
200 dimensions accuracy: 0.93
500 dimensions accuracy: 0.9283333333333333
1000 dimensions accuracy: 0.9383333333333334


In [140]:
print("modele 1000 articles")
compare_categ_log(["economie","societe"],df,model_1000_100dim,100)
compare_categ_log(["economie","societe"],df,model_1000_200dim,200)
compare_categ_log(["economie","societe"],df,model_1000_500dim,500)
compare_categ_log(["economie","societe"],df,model_1000_1000dim,1000)

modele 1000 articles
100 dimensions accuracy: 0.825
200 dimensions accuracy: 0.8083333333333333
500 dimensions accuracy: 0.8116666666666666
1000 dimensions accuracy: 0.79


In [141]:
print("modele 8200 articles")
compare_categ_log(["economie","societe"],df,model_8200_100dim,100)
compare_categ_log(["economie","societe"],df,model_8200_200dim,200)
compare_categ_log(["economie","societe"],df,model_8200_500dim,500)
compare_categ_log(["economie","societe"],df,model_8200_1000dim,1000)

modele 8200 articles
100 dimensions accuracy: 0.905
200 dimensions accuracy: 0.9166666666666666
500 dimensions accuracy: 0.9166666666666666
1000 dimensions accuracy: 0.9083333333333333


In [152]:
print("cutoff 500dim")  # no amelioration vs 0.91
compare_categ_log(["economie","societe"],df,model_8200_500dim,100)
compare_categ_log(["economie","societe"],df,model_8200_500dim_50cutoff,200)
compare_categ_log(["economie","societe"],df,model_8200_500dim_100cutoff,500)
compare_categ_log(["economie","societe"],df,model_8200_500dim_200cutoff,1000)

cutoff 500dim
100 dimensions accuracy: 0.9166666666666666
200 dimensions accuracy: 0.9083333333333333
500 dimensions accuracy: 0.9133333333333333
1000 dimensions accuracy: 0.9116666666666666


In [136]:
compare_categ_log(["politique","societe"],df,model_1000_100dim,100)
compare_categ_log(["politique","societe"],df,model_1000_200dim,200)
compare_categ_log(["politique","societe"],df,model_1000_500dim,500)
compare_categ_log(["politique","societe"],df,model_1000_1000dim,1000)

100 dimensions accuracy: 0.8216666666666667
200 dimensions accuracy: 0.7833333333333333
500 dimensions accuracy: 0.83
1000 dimensions accuracy: 0.785


In [153]:
print("cutoff 500dim") # amelioration vs 0.81, see below
compare_categ_log(["politique","societe"],df,model_8200_500dim,100)
compare_categ_log(["politique","societe"],df,model_8200_500dim_50cutoff,200)
compare_categ_log(["politique","societe"],df,model_8200_500dim_100cutoff,500)
compare_categ_log(["politique","societe"],df,model_8200_500dim_200cutoff,1000)

cutoff 500dim
100 dimensions accuracy: 0.8416666666666667
200 dimensions accuracy: 0.8383333333333334
500 dimensions accuracy: 0.8283333333333334
1000 dimensions accuracy: 0.8316666666666667


In [139]:
compare_categ_log(["politique","societe"],df,model_8200_100dim,100)
compare_categ_log(["politique","societe"],df,model_8200_200dim,200)
compare_categ_log(["politique","societe"],df,model_8200_500dim,500)
compare_categ_log(["politique","societe"],df,model_8200_1000dim,1000)

100 dimensions accuracy: 0.8366666666666667
200 dimensions accuracy: 0.84
500 dimensions accuracy: 0.8133333333333334
1000 dimensions accuracy: 0.8416666666666667


In [142]:
compare_categ_log(["politique","societe","economie"],df,model_1000_100dim,100)
compare_categ_log(["politique","societe","economie"],df,model_1000_200dim,200)
compare_categ_log(["politique","societe","economie"],df,model_1000_200dim,500)
compare_categ_log(["politique","societe","economie"],df,model_1000_1000dim,1000)

100 dimensions accuracy: 0.7211111111111111
200 dimensions accuracy: 0.7177777777777777
500 dimensions accuracy: 0.7366666666666667
1000 dimensions accuracy: 0.7133333333333334


In [143]:
compare_categ_log(["politique","societe","economie"],df,model_8200_100dim,100)
compare_categ_log(["politique","societe","economie"],df,model_8200_200dim,200)
compare_categ_log(["politique","societe","economie"],df,model_8200_200dim,500)
compare_categ_log(["politique","societe","economie"],df,model_8200_1000dim,1000)

100 dimensions accuracy: 0.8066666666666666
200 dimensions accuracy: 0.7888888888888889
500 dimensions accuracy: 0.8077777777777778
1000 dimensions accuracy: 0.8188888888888889


In [99]:
model_1000_100dim.most_similar("économie")

[('santé', 0.812455415725708),
 ('transition', 0.8102002739906311),
 ('budget', 0.7560843229293823),
 ('enseignement', 0.7560242414474487),
 ('finance', 0.7490084767341614),
 ('ex-premier', 0.7483202219009399),
 ('immigration', 0.7432029247283936),
 ('intérieur', 0.743035614490509),
 ('culture', 0.7387093305587769),
 ('Pellerin', 0.7344215512275696)]

In [148]:
model_8200_100dim.most_similar("économie")

[('croissance', 0.5927355885505676),
 ('finance', 0.5501879453659058),
 ('compétitivité', 0.5379248261451721),
 ('productif', 0.5106614828109741),
 ('relance', 0.5067898035049438),
 ('budget', 0.5056710839271545),
 ('économique', 0.49872809648513794),
 ('déséquilibre', 0.47295713424682617),
 ('structurel', 0.47245392203330994),
 ('budgétaire', 0.47141095995903015)]

In [171]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
def compare_categ_log_1vsall(categories,df,model_vec):
    df_sampled = df[df.label.isin(categories)]
    df_train, df_test = model_selection.train_test_split(df_sampled, test_size=0.3)
    ## get target
    y_train = df_train["label"].values
    y_test = df_test["label"].values
    df_train['doc_vector'] = df_train.tokens.apply(document_vector,model=model_vec)
    df_test['doc_vector'] = df_test.tokens.apply(document_vector,model=model_vec)
    train = df_train['doc_vector'].tolist()
    test = df_test['doc_vector'].tolist()
    clf = OneVsRestClassifier(SVC()).fit(train, y_train)
    y_pred=clf.predict(test)
    cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
    print(cnf_matrix)
    print(classification_report(y_test, y_pred))
    # fig, ax = plt.subplots()
    # classes = np.unique(y_test)
    # sns.heatmap(cnf_matrix, annot=True, fmt='d', ax=ax, cmap=plt.cm.Blues, 
    #             cbar=False)
    # ax.set(xlabel="Pred", ylabel="True", xticklabels=classes, 
    #     yticklabels=classes, title="Confusion matrix")
    # plt.yticks(rotation=0)

In [172]:
compare_categ_log_1vsall(["politique","societe","economie"],df,model_1000_100dim)

[[244  25  36]
 [ 28 228  36]
 [ 47  62 194]]
              precision    recall  f1-score   support

    economie       0.76      0.80      0.78       305
   politique       0.72      0.78      0.75       292
     societe       0.73      0.64      0.68       303

    accuracy                           0.74       900
   macro avg       0.74      0.74      0.74       900
weighted avg       0.74      0.74      0.74       900



In [174]:
compare_categ_log_1vsall(["politique","societe","economie"],df,model_8200_100dim)

[[280  20  14]
 [ 18 234  29]
 [ 25  53 227]]
              precision    recall  f1-score   support

    economie       0.87      0.89      0.88       314
   politique       0.76      0.83      0.80       281
     societe       0.84      0.74      0.79       305

    accuracy                           0.82       900
   macro avg       0.82      0.82      0.82       900
weighted avg       0.83      0.82      0.82       900



In [175]:
compare_categ_log_1vsall(["politique","societe","economie"],df,model_frWac)

[[260  21  17]
 [ 22 245  30]
 [ 24  53 228]]
              precision    recall  f1-score   support

    economie       0.85      0.87      0.86       298
   politique       0.77      0.82      0.80       297
     societe       0.83      0.75      0.79       305

    accuracy                           0.81       900
   macro avg       0.82      0.81      0.81       900
weighted avg       0.82      0.81      0.81       900



In [176]:
compare_categ_log_1vsall(["politique","societe","economie"],df,model_frWac_skip)

[[259  14  13]
 [ 24 250  50]
 [ 25  52 213]]
              precision    recall  f1-score   support

    economie       0.84      0.91      0.87       286
   politique       0.79      0.77      0.78       324
     societe       0.77      0.73      0.75       290

    accuracy                           0.80       900
   macro avg       0.80      0.80      0.80       900
weighted avg       0.80      0.80      0.80       900



In [177]:
from sklearn.neighbors import KNeighborsClassifier
def compare_categ_log_knearest(categories,df,model_vec,nb_neighbor):
    df_sampled = df[df.label.isin(categories)]
    # print(df_sampled)
    ## split dataset
    df_train, df_test = model_selection.train_test_split(df_sampled, test_size=0.3)
    ## get target
    y_train = df_train["label"].values
    y_test = df_test["label"].values
    df_train['doc_vector'] = df_train.tokens.apply(document_vector,model=model_vec)
    df_test['doc_vector'] = df_test.tokens.apply(document_vector,model=model_vec)
    train = df_train['doc_vector'].tolist()
    test = df_test['doc_vector'].tolist()
    clf = KNeighborsClassifier(n_neighbors=nb_neighbor)
    clf.fit(train, y_train)
    y_pred=clf.predict(test)
    cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
    print(cnf_matrix)
    print(classification_report(y_test, y_pred))
    # fig, ax = plt.subplots()
    # classes = np.unique(y_test)
    # sns.heatmap(cnf_matrix, annot=True, fmt='d', ax=ax, cmap=plt.cm.Blues, 
    #             cbar=False)
    # ax.set(xlabel="Pred", ylabel="True", xticklabels=classes, 
    #     yticklabels=classes, title="Confusion matrix")
    # plt.yticks(rotation=0)

In [178]:
compare_categ_log_knearest(["politique","societe","economie"],df,model_1000_100dim,1)

[[224  31  38]
 [ 45 180  75]
 [ 68  71 168]]
              precision    recall  f1-score   support

    economie       0.66      0.76      0.71       293
   politique       0.64      0.60      0.62       300
     societe       0.60      0.55      0.57       307

    accuracy                           0.64       900
   macro avg       0.63      0.64      0.63       900
weighted avg       0.63      0.64      0.63       900



In [192]:
compare_categ_log_knearest(["politique","societe","economie"],df,model_1000_100dim,10)

[[241   9  34]
 [ 44 219  48]
 [ 59  63 183]]
              precision    recall  f1-score   support

    economie       0.70      0.85      0.77       284
   politique       0.75      0.70      0.73       311
     societe       0.69      0.60      0.64       305

    accuracy                           0.71       900
   macro avg       0.71      0.72      0.71       900
weighted avg       0.72      0.71      0.71       900



In [179]:
compare_categ_log_knearest(["politique","societe","economie"],df,model_8200_100dim,1)

[[239  24  21]
 [ 21 233  60]
 [ 29  61 212]]
              precision    recall  f1-score   support

    economie       0.83      0.84      0.83       284
   politique       0.73      0.74      0.74       314
     societe       0.72      0.70      0.71       302

    accuracy                           0.76       900
   macro avg       0.76      0.76      0.76       900
weighted avg       0.76      0.76      0.76       900



In [189]:
compare_categ_log_knearest(["politique","societe","economie"],df,model_8200_100dim,10)

[[252  19  14]
 [ 18 261  25]
 [ 33  68 210]]
              precision    recall  f1-score   support

    economie       0.83      0.88      0.86       285
   politique       0.75      0.86      0.80       304
     societe       0.84      0.68      0.75       311

    accuracy                           0.80       900
   macro avg       0.81      0.81      0.80       900
weighted avg       0.81      0.80      0.80       900



In [193]:
compare_categ_log_knearest(["politique","societe","economie"],df,model_frWac,1)

[[235  40  27]
 [ 29 221  39]
 [ 23  88 198]]
              precision    recall  f1-score   support

    economie       0.82      0.78      0.80       302
   politique       0.63      0.76      0.69       289
     societe       0.75      0.64      0.69       309

    accuracy                           0.73       900
   macro avg       0.73      0.73      0.73       900
weighted avg       0.74      0.73      0.73       900



In [196]:
compare_categ_log_knearest(["politique","societe","economie"],df,model_frWac,10)

[[301  26  11]
 [ 23 247  21]
 [ 27  75 169]]
              precision    recall  f1-score   support

    economie       0.86      0.89      0.87       338
   politique       0.71      0.85      0.77       291
     societe       0.84      0.62      0.72       271

    accuracy                           0.80       900
   macro avg       0.80      0.79      0.79       900
weighted avg       0.80      0.80      0.79       900



In [162]:
from sklearn.neural_network import MLPClassifier
def compare_categ_multiperceptron(categories,df,model_vec):
    df_sampled = df[df.label.isin(categories)]
    # print(df_sampled)
    ## split dataset
    df_train, df_test = model_selection.train_test_split(df_sampled, test_size=0.3)
    ## get target
    y_train = df_train["label"].values
    y_test = df_test["label"].values
    df_train['doc_vector'] = df_train.tokens.apply(document_vector,model=model_vec)
    df_test['doc_vector'] = df_test.tokens.apply(document_vector,model=model_vec)
    train = df_train['doc_vector'].tolist()
    test = df_test['doc_vector'].tolist()
    clf = MLPClassifier(random_state=1, max_iter=300).fit(train, y_train)
    y_pred=clf.predict(test)
    cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
    cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
    print10" dimensions accuracy: "+str(accuracy_score(y_test, y_pred)))
    # print(classification_report(y_test, y_pred))
    print(cnf_matrix)
    # print(classification_report(y_test, y_pred))
    # fig, ax = plt.subplots()
    # classes = np.unique(y_test)
    # sns.heatmap(cnf_matrix, annot=True, fmt='d', ax=ax, cmap=plt.cm.Blues, 
    #             cbar=False)
    # ax.set(xlabel="Pred", ylabel="True", xticklabels=classes, 
    #     yticklabels=classes, title="Confusion matrix")
    # plt.yticks(rotation=0)

In [170]:
compare_categ_multiperceptron(["politique","societe","economie"],df,model_1000_100dim)

 dimensions accuracy: 0.7588888888888888
[[251  25  29]
 [ 33 225  36]
 [ 38  56 207]]


In [163]:
compare_categ_multiperceptron(["politique","societe","economie"],df,model_8200_100dim)

 dimensions accuracy: 0.7966666666666666
[[267  26  21]
 [ 14 234  49]
 [ 20  53 216]]


In [165]:
compare_categ_multiperceptron(["politique","societe","economie"],df,model_8200_500dim)

 dimensions accuracy: 0.8088888888888889
[[257  23  24]
 [ 17 221  50]
 [ 18  40 250]]


In [166]:
compare_categ_multiperceptron(["politique","societe","economie"],df,model_8200_1000dim)

 dimensions accuracy: 0.7977777777777778
[[252  23  23]
 [ 16 240  44]
 [ 28  48 226]]


In [164]:
compare_categ_multiperceptron(["politique","societe","economie"],df,model_frWac)

 dimensions accuracy: 0.81
[[265  23  19]
 [ 19 236  45]
 [ 15  50 228]]


In [169]:
compare_categ_multiperceptron(["politique","societe","economie"],df,model_frWac_skip)

 dimensions accuracy: 0.8
[[256  21  20]
 [ 17 258  25]
 [ 21  76 206]]
